### ISSUE TITLE
As a moderator, I want Projects automatically organized into list pages so I don't have to manually manage these pages.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#280]
# testing notes
This issue refers to the project list views on the current CDH site - [sponsored projects](https://cdh.princeton.edu/projects/), [staff projects](https://cdh.princeton.edu/projects/staff/), and [working groups](https://cdh.princeton.edu/projects/working-groups/) (we treat working groups as a type of project for simplicity).

## as a user
We want to make sure that the list pages exist on the new site at the same URLs, and that the same projects appear on each list. The corresponding URLs on the test site are:

- <https://cdh-test-web.princeton.edu/projects/>
- <https://cdh-test-web.princeton.edu/projects/staff/>
- <https://cdh-test-web.princeton.edu/projects/working-groups/>

check a few projects on each list and confirm that things look the same. there may be small differences in the images displayed on the project cards; this is an acceptable difference (unless they look totally horrendous).

note that the working groups page on the current site doesn't have a page intro (the short bit of text at the top of the list), but the one on the test site does. I think this is actually a bug we're fixing, since if you edit the working groups page on the current site, you can see there is in fact text there - it's just not showing up. let me know if this doesn't make sense.

## as a moderator
In the [admin site](https://cdh-test-web.princeton.edu/cms/), expand the main page tree ("Pages"), look for "Sponsored Projects" underneath "home", and confirm that link pages have been created for each of the project list pages underneath "Projects". If you edit one of these special link pages, you should only see a title and a url for the page within the site. These special pages are used to manage the site's navigation menu; the actual display of projects on the list page is handled via code. Try changing the title and see if the name of the page in the site's navigation menu also changes.

also in the admin site, check out the menu on the left called "Snippets". this is new; it's where small pieces of text (like page intros) will be stored and edited. you should be able to find the page intro snippet for the Working Groups list page here; go ahead and edit it and see if your changes are reflected when you visit the page. you might need to refresh multiple times to see the changes.

# dev notes
## views
- [x] `ProjectListView`
- [x] `StaffProjectListView`
- [x] `WorkingGroupListView`

**Comment by manawinters** [comment]
test

**Comment by thatbudakguy** [comment]
test reply

**Comment by manawinters** [comment]
- The folder image reads “[Sponsored Projects](https://cdh-test-web.princeton.edu/projects/)” in the test site, but just "[Projects](https://cdh.princeton.edu/projects/)" in the production site
- The 4 DH Working Groups fall under "Projects” (as well as under DH Working Groups) in the production site, but not in test site
- The dropdown option (to toggle to other Projects) on the righthand side does not work in the test site
- The order of the projects is in alphabetical order in the production site, but Princeton Geniza and New Languages are the first two in the test site (then it’s in alphabetical order)
- Perhaps not as important to note - in both the production and test sites, across all projects, some names on the lefthand side (under project director or instructors, for example) are emboldened; others are not
- The folder image reads “[Staff Projects](https://cdh-test-web.princeton.edu/projects/staff/)” in the test site, but “[Staff and Postdoctoral Fellow Projects](https://cdh.princeton.edu/projects/staff/)” in the production site
- Projects are alphabetized in the production, but not test site
- For DH Working Groups in the test site, there is a page intro, but then no projects

- In the Wagtail admin site, I successfully changed the title, which was reflected in the test site

- The edits I made in Snippets -> DH Working Groups did not work, despite multiple refreshes

**Comment by thatbudakguy** [comment]
- small name differences ("sponsored projects" vs "projects", "staff projects" vs "staff and postdoctoral projects") are ok for now
- DH working groups being listed as projects in production is a bug, so looks like we fixed it on the test site! that's good
- dropdown not working should be resolved now
- will look into the order thing, but for now I think it's not a problem
- bold names on the left-hand side indicate people with a profile. try clicking them to make sure the link works!
- DH working groups missing should be resolved now
- please try editing the snippets again; if you don't see changes try a hard refresh (cmd + shift + R on a mac)

@manawinters  please test again and let me know if any of these issues are recurring.

**Comment by manawinters** [comment]
- DH working groups only visible through dropdown

- Still not able to view updates in Snippets, despite multiple refreshes (including a hard refresh)

**Comment by thatbudakguy** [comment]
@manawinters rsk and I talked about the snippet refreshing issue and unfortunately it's not easy for us to solve, so we're going to ignore it for awhile - in practice the snippet text shouldn't change often, so it's not a huge issue. thanks for your thorough testing on this!

could you confirm that the DH working groups are now visible through both the menu link and the dropdown? if so, please close.
